/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package NeuralCryptography;

import TreeParityMachine.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Matt
 */
public class WeightDialog extends javax.swing.JDialog {
    /**
     * Creates new form EditJDialog
     */
    public WeightDialog(java.awt.Frame parent, boolean modal, TreeParityMachine TPMmachine, String clientName) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(getRootPane());
        this.setTitle("Váhy TPM klienta "+ clientName);

        Object[][] model = new Object[TPMmachine.getHiddenNeuronsCount()][TPMmachine.getInputNeuronsCount()];
        Object[] headers = new String[TPMmachine.getInputNeuronsCount()];
        int pom = TPMmachine.getInputNeuronsCount();
        for (int i = 0; i < TPMmachine.getHiddenNeuronsCount(); i++) {
            for (int j = 0; j < TPMmachine.getInputNeuronsCount(); j++) {
                model[i][j] = TPMmachine.getWeightValue(i*pom+j);
                headers[j] = "Vstupný neurón " + i;
        }            
        }
        jTable1.setModel(new DefaultTableModel(model,headers));
        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
